# Generated by Django 4.2.6 on 2026-09-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_archived',
            field=models.BooleanField(default=False),
        ),
    ]
