# Generated by Django 4.2.6 on 2026-09-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_student_archived'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created'], name='tasks_notif_user_id_f55c69_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['teacher', 'name'], name='tasks_subje_teacher_dc3199_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['teacher', 'created'], name='tasks_task_teacher_b87334_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['student', 'completed', 'created'], name='tasks_task_student_d15a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'score'], name='tasks_task_due_dat_accb08_idx'),
        ),
    ]
