# Generated by Django 5.2.6 on 2026-10-01 00:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_notification_tasks_notif_user_id_f55c69_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='entregas'),
        ),
    ]
