# Generated by Django 5.2.6 on 2026-10-04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_submission_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="entregas",
            ),
        ),
    ]
